config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#index'

  resources :albums, only: :index
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    artist = Artist.find(params[:artist_id])
    albums = artist.albums

    render json: {
      albums: albums.map { |album| render_album(album) },
      artist: artist.name
    }
  end

  private

  def render_album(album)
    render_to_string(
      partial: 'albums/album',
      locals: { album: album }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @artists = Artist.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/albums/_album.html.erb
<div class="card__row">
  <div class="card"
       data-controller="tooltip"
       data-tooltip-content="<%= album.title %>">
    <%= image_tag album.image_url, class: "avatar-lg" %>
  </div>
</div>

app/views/albums/index.html.erb
<%= render @albums %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stimulus Rails Tutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="page-wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div data-controller="albums-loader"
     data-albums-loader-url="<%= albums_path %>"
>

  <div class="section">
    <h1 class="main-heading">Artists</h1>
    <div class="card__slider" data-controller="slider">
      <div class="card__container" data-target="slider.container">
        <% @artists.each do |artist| %>
          <div class="card">
            <%= image_tag artist.image_url,
                          class: 'avatar-circle avatar-4xl avatar-grow',
                          data: {
                            id: artist.id,
                            target: 'albums-loader.artist',
                            action: 'click->albums-loader#load'
                          }
            %>
            <h5 class="text-center"><%= artist.name %></h5>
          </div>
        <% end %>
      </div>
      <div class="chevron chevron-right" data-action="click->slider#next">
        <i class="fas fa-chevron-right"></i>
      </div>
      <div class="chevron chevron-left" data-action="click->slider#prev">
        <i class="fas fa-chevron-left"></i>
      </div>
    </div>
  </div>

  <div class="section">
    <h2 class="heading">Albums: <span data-target="albums-loader.artistName"></span></h2>
    <div class="card__container" data-target="albums-loader.container"></div>
  </div>

</div>